status = info
name = SparkLoggingSyslog

rootLogger.level = info
rootLogger.appenderRef.console.ref = CONSOLE

appender.CONSOLE.type = Console
appender.CONSOLE.name = CONSOLE
appender.CONSOLE.target = SYSTEM_ERR
appender.CONSOLE.layout.type = PatternLayout
appender.CONSOLE.layout.pattern = [${env:LOG_TAG_HOSTNAME:-${env:HOSTNAME:-unknown}}]${env:LOG_TAG_APPLICATION:-}${env:LOG_TAG_ACTION:-}${env:LOG_TAG_SECURITY:-}${env:LOG_TAG_CUSTOM:-} %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex

appender.SYSLOG.type = Syslog
appender.SYSLOG.name = SYSLOG
appender.SYSLOG.host = ${sys:syslog.host:-localhost}
appender.SYSLOG.port = ${sys:syslog.port:-514}
appender.SYSLOG.protocol = ${sys:syslog.protocol:-UDP}
appender.SYSLOG.facility = ${sys:syslog.facility:-LOCAL1}
appender.SYSLOG.appName = spark-${env:LOG_TAG_HOSTNAME:-${env:HOSTNAME:-unknown}}

appender.AUDIT.type = RollingFile
appender.AUDIT.name = AUDIT
appender.AUDIT.fileName = ${env:LOG_DIR:-/logs}/spark-audit.log
appender.AUDIT.filePattern = ${env:LOG_DIR:-/logs}/spark-audit-%d{yyyy-MM-dd}.log
appender.AUDIT.layout.type = PatternLayout
appender.AUDIT.layout.pattern = [${env:LOG_TAG_HOSTNAME:-${env:HOSTNAME:-unknown}}]${env:LOG_TAG_APPLICATION:-}[Audit]${env:LOG_TAG_SECURITY:-}${env:LOG_TAG_CUSTOM:-} %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex
appender.AUDIT.policies.type = Policies
appender.AUDIT.policies.time.type = TimeBasedTriggeringPolicy
appender.AUDIT.policies.time.interval = 1

appender.ACCESS.type = RollingFile
appender.ACCESS.name = ACCESS
appender.ACCESS.fileName = ${env:LOG_DIR:-/logs}/jetty-access.log
appender.ACCESS.filePattern = ${env:LOG_DIR:-/logs}/jetty-access-%d{yyyy-MM-dd}.log
appender.ACCESS.layout.type = PatternLayout
appender.ACCESS.layout.pattern = [${env:LOG_TAG_HOSTNAME:-${env:HOSTNAME:-unknown}}]${env:LOG_TAG_APPLICATION:-}[Access]${env:LOG_TAG_ACTION:-}${env:LOG_TAG_CUSTOM:-} %m%n
appender.ACCESS.policies.type = Policies
appender.ACCESS.policies.time.type = TimeBasedTriggeringPolicy
appender.ACCESS.policies.time.interval = 1

logger.spark.name = org.apache.spark
logger.spark.level = info

logger.audit.name = org.apache.spark
logger.audit.level = info
logger.audit.appenderRef.console.ref = CONSOLE
logger.audit.appenderRef.AUDIT.ref = AUDIT
logger.audit.appenderRef.SYSLOG.ref = SYSLOG
logger.audit.additivity = false

logger.access.name = org.sparkproject.jetty.server.RequestLog
logger.access.level = info
logger.access.appenderRef.ACCESS.ref = ACCESS
logger.access.appenderRef.SYSLOG.ref = SYSLOG
logger.access.additivity = false

