# Spark on YARN (no Hive)
# Mounted for logging practice

spark.master                     yarn
spark.submit.deployMode          client
spark.driver.host                spark-client
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:8020/spark-history
spark.history.fs.logDirectory    hdfs://namenode:8020/spark-history
spark.yarn.historyServer.allowTracking true
spark.yarn.historyServer.address sparkhistoryserver:18080
